FROM postgres:latest

# Copy any custom configuration files, if you have any
# COPY custom-config.conf /etc/postgresql/custom-config.conf

# Set environment variables, if necessary
ENV POSTGRES_DB=hotel_v2
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=massimo

# Expose the PostgreSQL port
EXPOSE 5432
